// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyncjitqkcxkmotzokkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5bmNqaXRxa2N4a21vdHpva2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNjA5MzUsImV4cCI6MjA4NjczNjkzNX0.TZpfsfDHSsd-cVSOI_1kVrn3XcrbziWrmElVdvW4lQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});