// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbzltbnzixzwyzodebmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiemx0Ym56aXh6d3l6b2RlYm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MjI3MjcsImV4cCI6MjA3NDk5ODcyN30.I8WYsPJ-fQVsHCvO79TmX6vYyhnyTBOHhEpLkaV8d9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});